# Sample .travis.yml for R projects

language: r
#warnings_are_errors: true
sudo: required
     
env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_=FALSE

r_packages:
  - PerformanceAnalytics
  - covr

#install:     
r_github_packages:
  - cloudcello/blotter
#  - cloudcello/quantstrat

# this also works as well as installing via r_packages:  
#before_script:   
#  - Rscript -e 'install.packages("covr", repos="http://cran.rstudio.com")'

after_success:
  - Rscript -e 'library(covr);codecov()'  
